version: '3.8'
services:
  app:
   build: .
   container_name: spring_app
   ports:
     - "8080:8080"	
   depends_on:
     - postgres
  postgres:
    image: postgres:15-alpine  
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser      
      POSTGRES_PASSWORD: mypassword123  
      POSTGRES_DB: mydatabase    
    ports:
      - "5432:5432"              
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - my_network

volumes:
  postgres_data:                 

networks:
  my_network:
    driver: bridge               
